---
- name: install nginx from apt
  become: yes
  apt:
    update_cache: no
    name: nginx
  tags:
    - setup
    - nginx-setup

- name: ensure /etc/nginx/etc exists
  become: yes
  file:
    path: "{{ nginx_etc }}"
    state: directory
    owner: root
    group: root
  when:
    - allow_from is defined

- name: replace the default nginx config
  become: yes
  template:
      src: etc/nginx/nginx.conf
      dest: /etc/nginx/nginx.conf
  tags:
    - nginx-setup
    - nginx-config
  notify:
    - reload nginx

- name: create whitelist file
  become: yes
  template:
    src: trustedips.conf
    dest: "{{ nginx_etc }}/trustedips.conf"
  tags:
    - nginx-setup
    - nginx-whitelist
  when:
    - allowed_from is defined
  notify:
    - reload nginx

- name: create sites-available dir
  become: yes
  file:
    path: "{{ nginx_available }}"
    state: directory

- name: create sites-enabled dir
  become: yes
  file: 
    path: "{{ nginx_enabled }}"
    state: directory
  tags:
    - nginx-setup
    - nginx-sites
